### ISSUE TITLE
Test Install OS, but "Due to the chip crisis, Raspberry Pi are mostly out of stock"

### ISSUE THREAD

**Issue by PIRenPIR** [PiRogueToolSuite/pirogue-os#1]
Hello! 

I wanted to test the pirogue-os, but no luck, Raspberry pi are out of stock... 
Anyone knows where to buy one please?

Meanwhile, i created a virtual one, to test generic PI OS install :-)
Here is the documentation i share:
https://www.consultingit.fr/fr/install-raspberry-pi-os-on-vmware
If you like it, please vote 5/5 Thank you by advance

Regards

**Comment by U039b** [comment]
You can visit https://rpilocator.com/ to check for availability.

**Comment by PIRenPIR** [comment]
Thank you very much
I updated the documentation
https://www.consultingit.fr/fr/install-raspberry-pi-os-on-vmware#rpilocator
you can close this issue, or let it open if people want to look here where to buy a raspberry
Regards
