### ISSUE TITLE
PiRogue as Onion Service

### ISSUE THREAD

**Issue by dawidol** [PiRogueToolSuite/pirogue-os#14]
Hi I want to see if it was possible to monitor PiRogue web interface over a TOR onion service, I add  this lines to /etc/tor/torrc

HiddenServiceDir /var/lib/tor/PiRogue/
HiddenServicePort 3000 127.0.0.1:3000
HiddenServicePort 8888 127.0.0.1:8888

After restar the service I try to enter with tor browser to OnionDomain.onion:3000 but I got this error:

Secure Connection Failed

An error occurred during a connection to jccvbn34dmmldlqb4cfcaeoocyeyuzqvnqoujdzkqlxyhap6nq2y2kid.onion:8888. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

Any help is welcome.

**Comment by dawidol** [comment]
So it looks like it was only problematic with the Onion Domain:
SuperLongOnionDomain.onion:3000 was not working, but SuperLongOnionDomain.onion:3000/login is working so it con now be monitor remotly

**Comment by U039b** [comment]
Oh, great!
