### ISSUE TITLE
Problem updating/upgrading the pirogue

### ISSUE THREAD

**Issue by b-u-g-s** [PiRogueToolSuite/pirogue-os#15]
Hi,

I just tried to update my pirogue for the first time (first install was done a few weeks ago).
I am getting an error, please see the 2x screenshots below
<img width="841" alt="Screenshot 2022-08-20 at 20 41 22" src="https://user-images.githubusercontent.com/8517705/185765140-1b18176c-00a0-4006-a879-1200b94d9ecc.png">

<img width="1140" alt="Screenshot 2022-08-20 at 22 32 34" src="https://user-images.githubusercontent.com/8517705/185765149-aef87253-d6bb-43fd-b1be-424c11a970bf.png">

Cheers,
B.

**Comment by U039b** [comment]
Sorry, for the delay. Do you have any update on this issue? It should be fixed with the latest versions of PiRogue packages.

**Comment by b-u-g-s** [comment]
No worries! It is working fine now :)
