### ISSUE TITLE
Out of date Frida

### ISSUE THREAD

**Issue by LVerneyPEReN** [PiRogueToolSuite/pirogue-os#18]
Frida is pinned to version 15.1.17 on the PiRogue repository. It is [a few releases behind](https://github.com/frida/frida/releases) and I have APKs which have issues with this version.

Typically, `Java.enumerateLoadedClassesSync()` would not return all of the loaded classes, but latest version of Frida would.

**Comment by U039b** [comment]
@CyrilBrulebois can you please have a look to this issue?

**Comment by CyrilBrulebois** [comment]
Upstream has released:

- 15.1.y up to 15.1.28
- 15.2.[012]
- 16.0.[012]

Would it make sense to try and catch up incrementally, starting with 15.1.28, possibly publishing it that to the PTS PPA? Then move to newer releases? Or should I try and package 16.0.2 directly, and deal with possible road blocks?

**Comment by CyrilBrulebois** [comment]
Hitting roadblocks with 15.1.28 and 16.0.2, I'll open issues upstream.

**Comment by CyrilBrulebois** [comment]
- 15.1.28 build failure filed as https://github.com/frida/frida/issues/2303
- 16.0.2 build failure filed as https://github.com/frida/frida/issues/2304

**Comment by LVerneyPEReN** [comment]
> Would it make sense to try and catch up incrementally, starting with 15.1.28, possibly publishing it that to the PTS PPA? Then move to newer releases? Or should I try and package 16.0.2 directly, and deal with possible road blocks?

My 2 cents on this, but AFAIK, Frida only support latest versions and deem 15.1.17 as no longer maintained. I would therefore recommend going directly for latest version (16.0.1/16.0.2 - the latter one being just an incremental bug fix for part of the tools, see https://github.com/frida/frida/releases where assets for 16.0.2 are only a subset of the assets).


Regarding the build issue, given the traceback, it might be worth reporting to [this repository](https://github.com/frida/frida-gum).


I'm not that much familiar with Debian packaging. Is there a reason for rebuilding Frida from source rather than using prebuilt binaries?

**Comment by CyrilBrulebois** [comment]
As I mentioned, incremental upgrades were supposed to be easy, and avoid stumbling upon several issues in one go. And indeed, there are regressions in various places…

We're building our own packages because prebuilt binaries were segfaulting.

**Comment by LVerneyPEReN** [comment]
> We're building our own packages because prebuilt binaries were segfaulting.

Ok! For anyone stumbling upon this issue and requiring a quick workaround, using latest `frida-server` from [Frida releases](https://github.com/frida/frida/) and installing frida-tools from pypy works for me:

```
$ python3 -m venv .venv
$ ./.venv/bin/pip install --upgrade setuptools wheel pip
$ ./.venv/bin/pip install frida-tools
$ # Then calling frida from there
$ ./.venv/bin/frida -U ...
```

(works if you need direct access to frida, not through `pirogue-ctl`).
