### ISSUE TITLE
Suricata db missing

### ISSUE THREAD

**Issue by doublem37** [PiRogueToolSuite/pirogue-os#22]
Hello

i made three pirogue installation on a raspeberry 3B.
Each time i ended with same issue in grafana no data from suricata on dashboard.

while query unflux db got this : 

> SHOW DATABASES;
name: databases
name
----
_internal
flows

Is this something i missed during installation ?

**Comment by U039b** [comment]
Hi,
As pointed out in [the documentation](https://pts-project.org/guides/g1/#pick-a-raspberry-pi), Suricata is disabled on devices having less then 1.5GB of RAM. So, that's why there is no `suricata` database in _influxdb_.

**Comment by doublem37** [comment]
i missed that :/ thx for ur quick reply.
Can i enabled suricata eventhoug i haven't enough memory ? (my raspberry got 1GB memory)

**Comment by U039b** [comment]
You can remove the 2 files created at the [pre-installation of the package](https://github.com/PiRogueToolSuite/deb-packages/blob/debian-12/pirogue-eve-collector/debian/pirogue-eve-collector.preinst), but if you do this, your system will crash.

**Comment by doublem37** [comment]
Thanks again for your reply and explanation.
I'll give a try

**Comment by U039b** [comment]
Do you have any update? Was I wrong?
